quiz/accounts/urls.py
from django.conf.urls import url

from . import views


app_name = 'accounts'
urlpatterns = [
    url(r'^login/', views.AccountLoginView.as_view(), name='login'),
    url(r'^register/', views.AccountRegisterView.as_view(), name='register'),
    url(r'^logout/', views.AccoutLogoutView.as_view(), name='logout'),
]

quiz/quiz/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.views.generic import TemplateView

from rest_framework_jwt.views import obtain_jwt_token, verify_jwt_token

from . import views


urlpatterns = [
    url(r'^api-token-auth/', obtain_jwt_token),
    url(r'^api-token-verify/', verify_jwt_token),
    url(r'^accounts/', include('accounts.urls')),
    url(r'^admin/', admin.site.urls),
    url(r'^api/quiz/$', views.QuizList.as_view()),
    url(r'^api/quiz/(?P<pk>[0-9]+)$', views.QuizDetail.as_view()),
    url(r'^api/myquizzes/$', views.MyQuizList.as_view()),
    url(r'^api/myquizzes/(?P<pk>[0-9]+)$', views.MyQuizDetail.as_view()),
    url(r'^api/myresults/$', views.MyResultList.as_view()),
    url(r'^api/myresults/(?P<pk>[0-9]+)$', views.MyResultDetail.as_view()),
    url(r'^api/question/$', views.QuestionList.as_view()),
    url(r'^api/question/(?P<pk>[0-9]+)$', views.QuestionDetail.as_view(), name='question-detail'),
    url(r'^api/choice/$', views.ChoiceList.as_view()),
    url(r'^api/choice/(?P<pk>[0-9]+)$', views.ChoiceDetail.as_view(), name='choice-detail'),
    url(r'^api/attempt/$', views.AttemptList.as_view()),
    url(r'^api/attempt/(?P<pk>[0-9]+)$', views.AttemptDetail.as_view()),
    url(r'^api/useranswer/$', views.UserAnswerList.as_view()),
    url(r'^api/useranswer/(?P<pk>[0-9]+)$', views.UserAnswerDetail.as_view()),
    url(r'^', TemplateView.as_view(template_name='quiz/index.html'), name='index'),
]

quiz/quiz/models.py
import datetime

from django.contrib.auth.models import User
from django.db import models
from django.utils import timezone

from .utils import is_question_correct


def timezone_now_plus_one_day():
    return timezone.now() + datetime.timedelta(days=1)


class Quiz(models.Model):
    created_by = models.ForeignKey(User)
    date_created = models.DateTimeField(default=timezone.now)
    expiration_date = models.DateTimeField(default=timezone_now_plus_one_day)
    title = models.CharField(max_length=200)

    def __str__(self):
        return self.title

    class Meta:
        verbose_name_plural = "quizzes"


class Question(models.Model):
    quiz = models.ForeignKey(Quiz, related_name='questions', on_delete=models.CASCADE)
    text = models.CharField(max_length=200)

    def __str__(self):
        return self.text


class Choice(models.Model):
    question = models.ForeignKey(Question, related_name='choices', on_delete=models.CASCADE)
    text = models.CharField(max_length=200)
    correct = models.BooleanField(default=False)

    def __str__(self):
        return self.text


class Attempt(models.Model):
    quiz = models.ForeignKey(Quiz)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    date_taken = models.DateTimeField(default=timezone.now)
    finished = models.BooleanField(default=False)

    def __str__(self):
        return str(self.user) + " : " + str(self.quiz)

    def get_score(self):
        questions = self.quiz.question_set.all()
        score = 0
        for question in questions:
            if is_question_correct(self, question):
                score = score + 1

        return "%d out of %d" % (score, questions.count())

    score = property(get_score)


class UserAnswer(models.Model):
    attempt = models.ForeignKey(Attempt, on_delete=models.CASCADE)
    answer = models.ForeignKey(Choice, on_delete=models.CASCADE)
    question = models.ForeignKey(Question, related_name="answers")

    def __str__(self):
        return self.answer.text

quiz/quiz/views.py
from rest_framework import generics
from rest_framework import permissions
from django.shortcuts import get_object_or_404
from django.utils import timezone

from .models import Quiz, Question, Choice, Attempt, UserAnswer
from .serializers import QuizSerializer, QuestionSerializer, ChoiceSerializer, AttemptSerializer, UserAnswerSerializer
from .permissions import IsTakenByAuthenticatedUser, IsOwner


class QuizList(generics.ListCreateAPIView):
    permission_classes = (permissions.IsAuthenticatedOrReadOnly,)
    serializer_class = QuizSerializer

    def perform_create(self, serializer):
        serializer.save(created_by=self.request.user)

    def get_queryset(self):
        return Quiz.objects.filter(expiration_date__gte=timezone.now())


class QuizDetail(generics.RetrieveUpdateDestroyAPIView):
    permission_classes = (IsOwner,)
    queryset = Quiz.objects.all()
    serializer_class = QuizSerializer


class QuestionList(generics.ListCreateAPIView):
    permission_classes = (permissions.IsAuthenticatedOrReadOnly,)
    queryset = Question.objects.all()
    serializer_class = QuestionSerializer


class QuestionDetail(generics.RetrieveUpdateDestroyAPIView):
    permission_classes = (permissions.IsAuthenticatedOrReadOnly,)
    queryset = Question.objects.all()
    serializer_class = QuestionSerializer


class ChoiceList(generics.ListCreateAPIView):
    permission_classes = (permissions.IsAuthenticatedOrReadOnly,)
    queryset = Choice.objects.all()
    serializer_class = ChoiceSerializer


class ChoiceDetail(generics.RetrieveUpdateDestroyAPIView):
    permission_classes = (permissions.IsAuthenticatedOrReadOnly,)
    queryset = Choice.objects.all()
    serializer_class = ChoiceSerializer


class MyQuizList(generics.ListAPIView):
    permission_classes = (permissions.IsAuthenticated,)
    serializer_class = QuizSerializer

    def get_queryset(self):
        return Quiz.objects.filter(created_by__exact=self.request.user)


class MyQuizDetail(generics.RetrieveUpdateDestroyAPIView):
    permission_classes = (permissions.IsAuthenticated, IsOwner)
    queryset = Quiz.objects.all()
    serializer_class = QuizSerializer


class MyResultList(generics.ListAPIView):
    permission_classes = (permissions.IsAuthenticated,)
    serializer_class = QuizSerializer

    def get_queryset(self):
        return Quiz.objects.filter(created_by__exact=self.request.user)


class MyResultDetail(generics.RetrieveUpdateDestroyAPIView):
    permission_classes = (permissions.IsAuthenticated,)
    queryset = Quiz.objects.all()
    serializer_class = QuizSerializer


class AttemptList(generics.ListCreateAPIView):
    permission_classes = (permissions.IsAuthenticatedOrReadOnly,)
    queryset = Attempt.objects.all()
    serializer_class = AttemptSerializer

    def perform_create(self, serializer):
        quiz = get_object_or_404(Quiz, pk=self.request.data.get('quiz'))
        if quiz.expiration_date >= timezone.now():
            serializer.save(user=self.request.user, quiz=quiz)

    def get_queryset(self):
        return Attempt.objects.filter(user__exact=self.request.user)


class AttemptDetail(generics.RetrieveUpdateDestroyAPIView):
    permission_classes = (permissions.IsAuthenticatedOrReadOnly, IsTakenByAuthenticatedUser)
    queryset = Attempt.objects.all()
    serializer_class = AttemptSerializer


class UserAnswerList(generics.ListCreateAPIView):
    permission_classes = (permissions.IsAuthenticatedOrReadOnly,)
    queryset = UserAnswer.objects.all()
    serializer_class = UserAnswerSerializer

    def perform_create(self, serializer):
        answer = get_object_or_404(Choice, pk=self.request.data.get('answer'))
        question = get_object_or_404(Question, pk=self.request.data.get('question'))
        serializer.save(answer=answer, question=question)


class UserAnswerDetail(generics.RetrieveUpdateDestroyAPIView):
    permission_classes = (permissions.IsAuthenticatedOrReadOnly,)
    queryset = UserAnswer.objects.all()
    serializer_class = UserAnswerSerializer

quiz/quiz/templates/base.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
    <head>
        <meta charset="utf-8">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" integrity="sha384-WskhaSGFgHYWDcbwN70/dfYBj47jz9qbsMId/iRN3ewGhXQFZCSftd1LZCfmhktB" crossorigin="anonymous">
        <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.13/css/all.css" integrity="sha384-DNOHZ68U8hZfKXOrtjWvjxusGo9WQnrNx2sqG0tfsghAvtVlRW3tvkXWZh58N9jp" crossorigin="anonymous">
        {% block head %}
        <title>Quiz Application</title>
        {% endblock %}
    </head>
    <body>
        {% include 'navigation.html' %}
        {% block body %}
        <p><strong>BLOCK BODY</strong></p>
        {% endblock %}
        <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js" integrity="sha384-smHYKdLADwkXOn1EmN1qk/HfnUcbVRZyYmZ4qpPea6sjB/pTJ0euyQp0Mk8ck+5T" crossorigin="anonymous"></script>
    </body>
</html>

quiz/quiz/templates/navigation.html
<nav class="navbar navbar-expand-lg navbar-dark bg-primary">
    <div class="container">
        <a class="navbar-brand" href="/" ui-sref="quizList">Dynaquiz</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarColor02" aria-controls="navbarColor02" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item active">
                    <a class="nav-link" href="/" ui-sref="quizList">Available Quizzes</a>
                </li>
                {% if user.is_authenticated %}
                <li class="nav-item active">
                    <a class="nav-link" ui-sref="results">My Results</a>
                </li>
                <li class="nav-item active">
                    <a class="nav-link" ui-sref="myQuizList">My Quizzes</a>
                </li>
                {% endif %}
            </ul>
            {% if user.is_authenticated %}
            <ul class="nav pull-right">
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle text-white" data-toggle="dropdown">
                        {{ user|capfirst }}
                        <span class="caret"></span>
                    </a>
                    <ul class="dropdown-menu">
                        <li><a href="{% url 'accounts:logout' %}" target="_self">Logout</a></li>
                    </ul>
                </li>
            </ul>
            {% else %}
            <form class="form-inline">
                <a class="btn btn-outline-light my-2 my-sm-0" target="_self" href="{% url 'accounts:login' %}">Login</a>
            </form>
            {% endif %}
        </div>
    </div>
</nav>

quiz/quiz/templates/pagination.html
<nav aria-label="Page navigation example">
  <ul class="pagination">
    <li class="page-item">
      <a class="page-link" href="#" aria-label="Previous">
        <span aria-hidden="true">&laquo;</span>
        <span class="sr-only" ng-hide="pagination.page == 0" ng-click="pagination.prevPage()">Previous</span>
      </a>
    </li>
    <li>
      <a class="page-link" href="#" aria-label="Next">
        <span aria-hidden="true">&raquo;</span>
        <span class="sr-only" ng-hide="pagination.page + 1 >= pagination.numPages" ng-click="pagination.nextPage()">Next</span>
      </a>
    </li>
  </ul>
</nav>