quiz/accounts/urls.py
from django.conf.urls import url

from . import views


app_name = 'accounts'
urlpatterns = [
    url(r'^login/', views.AccountLoginView.as_view(), name='login'),
    url(r'^register/', views.AccountRegisterView.as_view(), name='register'),
    url(r'^logout/', views.AccoutLogoutView.as_view(), name='logout'),
]

quiz/quiz/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.views.generic import TemplateView

from rest_framework_jwt.views import obtain_jwt_token, verify_jwt_token

from . import views


urlpatterns = [
    url(r'^api-token-auth/', obtain_jwt_token),
    url(r'^api-token-verify/', verify_jwt_token),
    url(r'^accounts/', include('accounts.urls')),
    url(r'^admin/', admin.site.urls),
    url(r'^api/quiz/$', views.QuizList.as_view()),
    url(r'^api/quiz/(?P<pk>[0-9]+)$', views.QuizDetail.as_view()),
    url(r'^api/myquizzes/$', views.MyQuizList.as_view()),
    url(r'^api/myquizzes/(?P<pk>[0-9]+)$', views.MyQuizDetail.as_view()),
    url(r'^api/myresults/$', views.MyResultList.as_view()),
    url(r'^api/myresults/(?P<pk>[0-9]+)$', views.MyResultDetail.as_view()),
    url(r'^api/question/$', views.QuestionList.as_view()),
    url(r'^api/question/(?P<pk>[0-9]+)$', views.QuestionDetail.as_view(), name='question-detail'),
    url(r'^api/choice/$', views.ChoiceList.as_view()),
    url(r'^api/choice/(?P<pk>[0-9]+)$', views.ChoiceDetail.as_view(), name='choice-detail'),
    url(r'^api/attempt/$', views.AttemptList.as_view()),
    url(r'^api/attempt/(?P<pk>[0-9]+)$', views.AttemptDetail.as_view()),
    url(r'^api/useranswer/$', views.UserAnswerList.as_view()),
    url(r'^api/useranswer/(?P<pk>[0-9]+)$', views.UserAnswerDetail.as_view()),
    url(r'^', TemplateView.as_view(template_name='quiz/index.html'), name='index'),
]

quiz/accounts/models.py
from django.db import models

# Create your models here.

quiz/accounts/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User


class LoginForm(forms.Form):
        username = forms.CharField(widget=forms.TextInput(attrs={
            'placeholder': 'Enter username',
            'class': 'form-control'
        }))
        password = forms.CharField(widget=forms.TextInput(attrs={
            'placeholder': 'Enter password',
            'class': 'form-control',
            'type': 'password'
        }))


class RegistrationForm(UserCreationForm):
    def __init__(self, *args, **kwargs):
        super(RegistrationForm, self).__init__(*args, **kwargs)
        self.fields['username'].widget.attrs['class'] = 'form-control'
        self.fields['password1'].widget.attrs['class'] = 'form-control'
        self.fields['password2'].widget.attrs['class'] = 'form-control'

    class Meta:
        model = User
        fields = ['username', 'password1', 'password2']

quiz/accounts/views.py
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponseRedirect
from django.views.generic import View
from django.shortcuts import render
from django.urls import reverse

from .forms import LoginForm, RegistrationForm


# Create your views here.
class AccountLoginView(View):
    def get(self, request):
        if request.user.is_authenticated:
            return HttpResponseRedirect(reverse('index'))

        form = LoginForm()
        args = {'form': form}
        return render(request, 'accounts/login.html', args)

    def post(self, request):
        form = LoginForm(request.POST)
        if form.is_valid():
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']
            user = authenticate(username=username, password=password)
            if user is not None:
                if user.is_active:
                    login(request, user)
                    return HttpResponseRedirect('/')

        messages.add_message(
            request, 50, 'Wrong login credentials.', extra_tags='danger'
        )
        return render(request, 'accounts/login.html', {'form': form})


class AccountRegisterView(View):
    def get(self, request):
        if request.user.is_authenticated:
            return HttpResponseRedirect(reverse('index'))
            
        form = RegistrationForm()
        args = {'form': form}
        return render(request, 'accounts/register.html', args)

    def post(self, request):
        form = RegistrationForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(
                request, 'Successfully Registered. You can now login.'
             )
            return HttpResponseRedirect(reverse('accounts:login'))
        return render(request, 'accounts/register.html', {'form': form})


class AccoutLogoutView(View):
    def get(self, request):
        logout(request)
        return HttpResponseRedirect(reverse('accounts:login'))

quiz/accounts/templates/accounts/login.html
{% extends 'base.html' %}

{% block body %}
<div class="container">
    <h1 class="text-center">Login</h1>
    <p class="text-center">
        {% if error_message %}
        <small class="text-danger">{{ error_message }}</small>
        {% endif %}
    </p>
    <p class="text-center">
        {% if messages %}
            {% for message in messages %}
            <small{% if message.tags %} class="text-{{ message.tags }}"{% endif %}>{{ message }}</small>
            {% endfor %}
        {% endif %}
    </p>
    <p class="text-center">
        <small>Not yet registered? <a href="{% url 'accounts:register' %}">Register here</a></small>
    </p>

    <form class="col-md-4 offset-md-4" method="post">
        {% csrf_token %}
        {% for field in form %}
            <div class="form-group">
                <small class="text-danger">{{ field.errors }}</small>
                <label>{{ field.label_tag}}</label>
                {{ field }}
            </div>
        {% endfor %}
        <button type="submit" class="btn btn-block btn-primary">Login</button>
    </form>
</div>
{% endblock %}

quiz/accounts/templates/accounts/register.html
{% extends 'base.html' %}
{% block body %}
<div class="container">
    <h1 class="text-center">Register</h1>
    <form class="col-md-4 offset-md-4" method="POST">
        {% csrf_token %}
        {% for field in form %}
            <div class="form-group">
                <small class="text-danger">{{ field.errors }}</small>
                <label>{{ field.label_tag}}</label>
                {{ field }}
            </div>
        {% endfor %}
        <input type="submit" class="btn btn-block btn-primary" value="Register">
    </form>
</div>
{% endblock %}